# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
sass:
  sass_dir: foundation/_scss
  style: compressed
excerpt_separator: "" # http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/

# site settings
title: Phaedryx
author: Tad Thorley
description: webby goodness
twitter_username: phaedryx
github_username: phaedryx

# theme
foundation:
  lang: en
